version: '2.1'

# sets up the infrastructure needed for development
services:

  postgres_db_migration:
    container_name: postgres-db-migration
    build:
      context: sql
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=test
      - PGUSER=test
      - PGPASSWORD=test
      - MIGRATION_LOCATIONS=filesystem:migrations,filesystem:data
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    healthcheck:
      test: "exit 0"

  postgres:
    image: postgres:9.6.3
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U test"
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres-db