server:
  port: 9000
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE
    demo: DEBUG

allowed.origins: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test